# Generated by Django 2.1.2 on 2018-10-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=3)),
                ('full_name', models.CharField(max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'frequencies',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=64)),
                ('network_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=64)),
                ('power', models.DecimalField(decimal_places=3, max_digits=12)),
                ('details', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mediumwave.Country')),
                ('freq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mediumwave.Frequency')),
                ('station_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mediumwave.Network')),
            ],
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortorder', models.IntegerField()),
                ('heading', models.CharField(max_length=128)),
                ('bodytext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmitter_name', models.CharField(max_length=64)),
                ('transmitter_slug', models.SlugField()),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='transmitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mediumwave.Transmitter'),
        ),
    ]
