# Generated by Django 2.1.2 on 2018-10-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumwave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='transmitter',
            name='transmitter_slug',
            field=models.SlugField(blank=True),
        ),
    ]
