# Generated by Django 2.1.2 on 2018-10-05 21:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediumwave', '0002_auto_20181005_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='network_name'),
        ),
        migrations.AlterField(
            model_name='transmitter',
            name='transmitter_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='transmitter_name'),
        ),
    ]
