# Generated by Django 2.1.2 on 2018-10-06 19:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediumwave', '0003_auto_20181005_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_slug',
            field=autoslug.fields.AutoSlugField(default='es', editable=False, populate_from='iso'),
            preserve_default=False,
        ),
    ]
