# Generated by Django 2.1.2 on 2018-10-12 19:58

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumwave', '0004_country_country_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('text', markdownx.models.MarkdownxField()),
                ('sortorder', models.IntegerField()),
            ],
        ),
    ]
