# Generated by Django 2.1.2 on 2018-10-14 16:34

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumwave', '0006_page_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='details',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
