# Generated by Django 2.1.2 on 2018-10-14 16:36

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumwave', '0007_auto_20181014_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='details',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
