# Generated by Django 2.1.2 on 2018-10-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumwave', '0008_auto_20181014_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='notes',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
