# Generated by Django 2.1.2 on 2018-10-17 19:37

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumwave', '0009_station_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textitem',
            name='bodytext',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
