# Generated by Django 2.1.2 on 2018-10-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumwave', '0010_auto_20181017_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmitter',
            name='iso',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
